In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 1]])
C = np.concatenate((A, B.T), axis=1)
print(f"The matrix:\n {C}")
print(f"Matrix rank:\n {np.linalg.matrix_rank(A, 0.0001)}, {np.linalg.matrix_rank(C, 0.0001)}")

A_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_1 = np.array([[0, 0, 0]])
C_1 = np.concatenate((A_1, B_1.T), axis=1)
print(f"New matrix:\n {C_1}")
print(f"The rank of the new matrix:\n {np.linalg.matrix_rank(A_1, 0.0001)}, {np.linalg.matrix_rank(C_1, 0.0001)}")

if len(A_1) > np.linalg.matrix_rank(A_1, 0.0001):
    print(f"The system has an infinite number of solutions.")
else:
    print(np.linalg.solve(A_1, B_2))


The matrix:
 [[1 2 3 2]
 [4 5 6 5]
 [7 8 9 1]]
Matrix rank:
 2, 3
New matrix:
 [[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
The rank of the new matrix:
 2, 2
The system has an infinite number of solutions.
