In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]


In [4]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -2.22044605e-16  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  1.38777878e-17]
 [ 0.00000000e+00  1.38777878e-17  1.00000000e+00]]


In [5]:
R1 = R[:2, :2]
print(R1)

[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]


In [6]:
B1 = np.dot(np.transpose(Q), B)[:2]
print(B1)

[-1.21860576e+01  3.55271368e-15]


In [7]:
X1 = np.linalg.solve(R1, B1)
print(X1)

[1.50000000e+00 3.92767275e-15]


In [8]:
X = np.append(X1, 0)
print(X)
print(np.linalg.norm(X))

[1.50000000e+00 3.92767275e-15 0.00000000e+00]
1.499999999999996


In [9]:
print(np.linalg.norm(np.dot(A, X) - B))

1.224744871391589


In [10]:
X = np.array([1.5, 1, 0.5])
print(np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B))

1.8708286933869707 15.297058540778355
